// AXIOM LIQUIDITY RESEARCH — Portfolio FED Complete Dataset
// S1 2005 → S1 2026

const SEMESTERS = [
  {id:"S1-2005",label:"S1 2005",year:2005,half:1,
   quadrant:"qt-high",
   quadrantLabel:"QT + Rising Rates",
   fedRate:"2.25% → 3.00%",
   balanceSheet:"Stable ~$837B — no QE, no QT",
   regime:"Rates rising steadily. Fed on a normalization path after years of accommodation. Balance sheet untouched. Classic restrictive stance without liquidity drain.",
   rationale:"Rates rising into restrictive territory demanded capital preservation. Heavy allocation to energy (oil supercycle), consumer staples and healthcare as defensive anchors. Short-duration bonds (SHY) as cash proxy. No growth or tech — duration risk too high.",
   anchor:"TLT 5% + SHY 5% — duration hedge and capital preservation",
   beta:"XLV 15%, XLP 10%, VTV 10% — defensive value, no rate sensitivity",
   alpha:"XLE 15%, XOM 10% — energy supercycle thesis"
  },
  {id:"S2-2005",label:"S2 2005",year:2005,half:2,
   quadrant:"qt-high",
   quadrantLabel:"QT + Rising Rates",
   fedRate:"3.00% → 4.25%",
   balanceSheet:"Stable — no QE, no QT",
   regime:"Rate cycle accelerating. Fed raised 5 times in H2 2005. Economy strong, housing heating up. Restrictive but not yet damaging.",
   rationale:"Doubled down on energy with XLE at 20% and XOM at 15% — oil approaching $70/barrel. Cyclicals (CAT, XLI) added on infrastructure spending momentum. Staples maintained as ballast. Defensive bias with selective sector conviction.",
   anchor:"XLV 10% + XLP 10% — defensives as buffer against rising rates",
   beta:"VTV 10%, XLI 10% — value and industrials in an accelerating economy",
   alpha:"XLE 20%, XOM 15%, CAT 5% — energy supercycle + infrastructure"
  },
  {id:"S1-2006",label:"S1 2006",year:2006,half:1,
   quadrant:"qt-high",
   quadrantLabel:"QT + Rising Rates",
   fedRate:"4.25% → 5.00%",
   balanceSheet:"Stable — balance sheet neutral",
   regime:"Fed approaching the terminal rate. Rates at 5% — credit begins to tighten. Housing market shows early cracks. Restrictive regime firmly in place.",
   rationale:"Maintained defensive/value posture. Energy still core (XLE, XOM). Materials (XLB) added on commodities momentum. SHY as cash equivalent. Avoided growth and duration entirely. Focus on sectors with real pricing power.",
   anchor:"SHY 5% — near-zero duration, cash-like protection",
   beta:"XLV 10%, XLP 10%, VTV 10% — defensive value core",
   alpha:"XLE 15%, XOM 10%, XLB 10% — commodity cycle"
  },
  {id:"S2-2006",label:"S2 2006",year:2006,half:2,
   quadrant:"qt-high",
   quadrantLabel:"QT + Rising Rates",
   fedRate:"5.00% → 5.25% (pause)",
   balanceSheet:"Stable — no changes",
   regime:"Fed pauses at 5.25%. Peak restrictive cycle. Economy still growing. Markets complacent. Credit spreads still tight. The calm before the subprime storm.",
   rationale:"With rates plateauing, allowed selective rotation into quality dividend payers. MCD and XOM generating strong cash flows. Healthcare overweight. VTV and XLB for diversification. BRK.B added as quality anchor — Buffett's all-weather portfolio quality.",
   anchor:"XLV 15% — defensive healthcare dominant",
   beta:"XLP 10%, VTV 10%, XLB 10%, XLE 10% — broad defensive/value exposure",
   alpha:"XOM 10%, MCD 10%, BRK.B 10% — quality compounders"
  },
  {id:"S1-2007",label:"S1 2007",year:2007,half:1,
   quadrant:"qt-high",
   quadrantLabel:"QT + Rising Rates",
   fedRate:"5.25% (held)",
   balanceSheet:"Stable — pre-crisis",
   regime:"Rates on hold at cycle peak. Subprime stress emerging but not yet systemic. Bear Stearns hedge funds collapse in June 2007. Last period of apparent normalcy.",
   rationale:"Rates held at 5.25% — maximum restrictive without escalation. Selected sectors with earnings resilience: healthcare, industrials, materials. BRK.B for quality. FCX (Freeport) as copper/commodity play — commodities still running. Avoided financials despite their apparent cheapness.",
   anchor:"XLV 15% — healthcare as defensive anchor",
   beta:"XLI 10%, VTV 10%, XLB 10% — value/industrial beta",
   alpha:"XLE 5%, FCX 10%, BRK.B 10% — commodities + quality"
  },
  {id:"S2-2007",label:"S2 2007",year:2007,half:2,
   quadrant:"qt-low",
   quadrantLabel:"QT + Falling Rates",
   fedRate:"5.25% → 4.25%",
   balanceSheet:"Stable — QE not yet deployed",
   regime:"Fed pivots to cuts as subprime crisis spreads. Three cuts in H2 2007. Balance sheet unchanged — no QE yet. A rare transitional quadrant: cutting into a deflationary shock.",
   rationale:"Decisive rotation to safety. Exited XLF and WFC (banks in trouble). Added GLD as first gold position. BRK.B, WMT, PG, JNJ — quality names with fortress balance sheets. XLP overweighted. The model correctly read the regime shift before the full crisis.",
   anchor:"XLV 15%, XLP 15% — maximum defensive weighting",
   beta:"VTV 10%, XLE 10% — value as rate-cut beneficiary",
   alpha:"BRK.B 10%, JNJ 10%, PG 10%, WMT 10%, GLD 10% — quality + gold hedge"
  },
  {id:"S1-2008",label:"S1 2008",year:2008,half:1,
   quadrant:"qt-low",
   quadrantLabel:"QT + Falling Rates",
   fedRate:"4.25% → 2.00%",
   balanceSheet:"Expanding but not QE — emergency lending facilities",
   regime:"Crisis accelerating. Fed in emergency cut mode. Bear Stearns collapses March 2008. Balance sheet grows via emergency facilities (TAF, TSLF) — not yet QE. Partial liquidity injection without broad stimulus.",
   rationale:"Maximum capital preservation. Heavy defensives (XLV, XLP, XLU). GLD at 10% as crisis hedge. SHY as near-cash. CVX retained — energy still elevated. BRK.B and JNJ as quality anchors. Avoided tech, financials, and anything growth-oriented.",
   anchor:"GLD 10%, SHY 5% — crisis hedge + cash equivalent",
   beta:"XLV 15%, XLP 10%, XLU 10% — utilities and defensives in crisis",
   alpha:"CVX 10%, BRK.B 10%, JNJ 10% — quality balance sheets"
  },
  {id:"S2-2008",label:"S2 2008",year:2008,half:2,
   quadrant:"qe-low",
   quadrantLabel:"QE + Zero Rates",
   fedRate:"2.00% → 0.00–0.25%",
   balanceSheet:"QE1 launched Nov 2008 — BS begins massive expansion",
   regime:"Lehman collapses September 2008. QE1 launched. ZIRP established. The single most important regime shift in modern monetary history. Maximum policy intervention.",
   rationale:"Despite QE onset, maintained defensive stance — regime shift too recent to rotate aggressively. TLT at 5% for duration upside. SHY as cash. Kept defensives (XLU, XLP). BRK.B and JNJ for quality. Avoided banks and tech still in freefall. WMT for recession-proof retail.",
   anchor:"GLD 15% — maximum gold weighting as monetary debasement hedge",
   beta:"XLU 15%, XLP 15% — recession defensives",
   alpha:"JNJ 10%, PG 10%, BRK.B 10%, WMT 10% — fortress balance sheets"
  },
  {id:"S1-2009",label:"S1 2009",year:2009,half:1,
   quadrant:"qe-low",
   quadrantLabel:"QE + Zero Rates",
   fedRate:"0.00–0.25% (ZIRP)",
   balanceSheet:"QE1 active — Fed BS expands to ~$2T",
   regime:"QE1 in full force. ZIRP established. March 2009 marks the market bottom. Correlation collapse, volatility compression begins. Regime of rising convexity to liquidity-sensitive assets.",
   rationale:"Pivoted to offense. QQQ at 15% as Nasdaq beta. AAPL and AMZN added — both showing resilience. Kept some defensives (XLV, JNJ) as safety net. IWM for small cap recovery beta. GLD retained as QE inflation hedge. First true risk-on positioning since 2006.",
   anchor:"GLD 10% — monetary debasement + volatility buffer",
   beta:"QQQ 15%, IWM 10%, XLK 10%, XLY 10% — broad recovery beta",
   alpha:"AAPL 10%, AMZN 10% — early digital economy leaders"
  },
  {id:"S2-2009",label:"S2 2009",year:2009,half:2,
   quadrant:"qe-low",
   quadrantLabel:"QE + Zero Rates",
   fedRate:"0.00–0.25% (ZIRP)",
   balanceSheet:"QE1 continuing — Fed BS ~$2.1T",
   regime:"Full reflation. QE1 mechanics working. Market recovery well underway. Correlations fallen, volatility compressed. The QE + Zero Rates quadrant in its purest form.",
   rationale:"Went fully offensive. Increased IWM to 15% — small caps lead in reflation. Added GOOG and MSFT alongside AAPL and AMZN. XLF for financial sector recovery. Reduced defensives. GLD retained. Portfolio 10 holdings all growth-oriented except gold.",
   anchor:"GLD 5% — tail hedge only, conviction is risk-on",
   beta:"QQQ 15%, IWM 15%, XLY 10%, XLF 10%, XLK 5% — maximum reflation beta",
   alpha:"AAPL 10%, AMZN 10%, GOOG 10%, MSFT 10% — the future mega-caps at low valuations"
  },
  {id:"S1-2010",label:"S1 2010",year:2010,half:1,
   quadrant:"qe-low",
   quadrantLabel:"QE + Zero Rates",
   fedRate:"0.00–0.25% (ZIRP)",
   balanceSheet:"QE1 ends March 2010 — brief pause before QE2",
   regime:"QE1 ends but ZIRP continues. Euro sovereign debt crisis triggers risk-off episode in H1 2010. Markets retrace. The transition between QE programs created temporary volatility.",
   rationale:"Challenging period — QE1 end created uncertainty. Maintained tech/growth bias (QQQ, AAPL) but suffered with GOOG and MSFT corrections. EEM exposure hurt by euro crisis contagion. GLD was the standout winner. Lesson: QE gaps create vol.",
   anchor:"GLD 5% — held through volatility, +13.4% in H1 2010",
   beta:"QQQ 15%, IWM 15%, XLY 10%, XLK 5% — kept growth bias",
   alpha:"AAPL 10%, AMZN 10%, GOOG 10%, MSFT 10% — conviction despite drawdown"
  },
  {id:"S2-2010",label:"S2 2010",year:2010,half:2,
   quadrant:"qe-low",
   quadrantLabel:"QE + Zero Rates",
   fedRate:"0.00–0.25% (ZIRP)",
   balanceSheet:"QE2 announced Nov 2010 — $600B additional",
   regime:"QE2 announced in November. Risk-on resumes forcefully. Emerging markets boom. Commodities surge on dollar weakness. Classic QE + Low Rates environment with commodity amplification.",
   rationale:"Rotated into QE2 beneficiaries: EEM (EM boom), DBC (commodities/dollar hedge), GLD increased. XLY for consumption recovery. PG as ballast. AAPL and GOOG as tech anchors. The QE2 trade was commodities + EM + US growth.",
   anchor:"GLD 10% — explicit anti-dollar QE2 hedge",
   beta:"EEM 15%, DBC 10%, XLY 10% — QE2 direct beneficiaries",
   alpha:"AAPL 10%, GOOG 10%, MSFT 10% — tech compounders"
  },
  {id:"S1-2011",label:"S1 2011",year:2011,half:1,
   quadrant:"qe-low",
   quadrantLabel:"QE + Zero Rates",
   fedRate:"0.00–0.25% (ZIRP)",
   balanceSheet:"QE2 active — $600B program running",
   regime:"QE2 peak. Commodities surging. EM equities leading. Dollar weak. China bubble concerns. BIDU added as China internet play. Commodities/EM momentum in full swing.",
   rationale:"QE2 in full force — leaned into commodity and EM theme. Added BIDU as China tech leverage. DBC at 10% for commodity exposure. GLD maintained. Tech core (QQQ, XLK) alongside EM. AMZN added for e-commerce secular growth.",
   anchor:"GLD 5% — monetary debasement hedge",
   beta:"EEM 15%, DBC 10%, QQQ 10%, XLY 10%, XLK 10% — QE2 theme",
   alpha:"AAPL 10%, AMZN 10%, BIDU 10% — growth leaders"
  },
  {id:"S2-2011",label:"S2 2011",year:2011,half:2,
   quadrant:"transition",
   quadrantLabel:"Transition",
   fedRate:"0.00–0.25% (ZIRP)",
   balanceSheet:"QE2 ends June 2011 — Operation Twist begins",
   regime:"QE2 ends. Operation Twist (maturity extension, not new money) replaces it. Europe sovereign crisis deepens. Risk-off. Markets volatile. A rare moment where ZIRP without QE created uncertainty.",
   rationale:"Rotated defensively with QE2 ending. GLD at 15% — gold peaked in September 2011. DBC maintained. Kept tech (QQQ, XLK, AAPL, GOOG) but reduced EM exposure. JNJ added for defensiveness. AMZN held despite drawdown.",
   anchor:"GLD 15% — maximum gold at QE2 end, peak monetary uncertainty",
   beta:"QQQ 10%, XLY 10%, XLK 10%, DBC 10% — diversified beta",
   alpha:"AAPL 10%, AMZN 10%, GOOG 10% — secular growers"
  },
  {id:"S1-2012",label:"S1 2012",year:2012,half:1,
   quadrant:"qe-low",
   quadrantLabel:"QE + Zero Rates",
   fedRate:"0.00–0.25% (ZIRP)",
   balanceSheet:"Operation Twist + sterilized purchases",
   regime:"Operation Twist running. European crisis stabilizing (Draghi 'whatever it takes' July 2012). Markets recovering. AAPL at historic run. Balanced regime between QE and zero rates.",
   rationale:"Balanced defensive/growth split. GLD and TLT as safety anchors. QQQ for growth. AAPL at peak momentum (+44% in H1). Healthcare and staples for balance. JNJ, PG, MSFT for quality.",
   anchor:"GLD 10%, TLT 10% — dual hedge: inflation + deflation",
   beta:"QQQ 10%, EEM 10% — growth and EM exposure",
   alpha:"AAPL 10%, MSFT 10%, JNJ 10%, PG 10% — quality + momentum"
  },
  {id:"S2-2012",label:"S2 2012",year:2012,half:2,
   quadrant:"qe-low",
   quadrantLabel:"QE + Zero Rates",
   fedRate:"0.00–0.25% (ZIRP)",
   balanceSheet:"QE3 launched Sept 2012 — open-ended $85B/month",
   regime:"QE3 open-ended — the most powerful QE signal ever. 'Infinity QE'. ZIRP. Maximum accommodation. Draghi backstop for Europe. Global risk appetite firmly positive.",
   rationale:"Maintained balanced posture despite QE3. AAPL reverting after June peak. Added EEM for EM QE beneficiary. GLD and TLT maintained as hedges. JNJ and PG for quality. Conservative approach despite extremely stimulative regime — the model valued balance over aggression.",
   anchor:"GLD 10%, TLT 10% — maintained dual hedge into QE3",
   beta:"QQQ 10%, EEM 10% — moderate risk-on",
   alpha:"AAPL 10%, JNJ 10%, PG 10%, MSFT 10% — quality anchors"
  },
  {id:"S1-2013",label:"S1 2013",year:2013,half:1,
   quadrant:"qe-low",
   quadrantLabel:"QE + Zero Rates",
   fedRate:"0.00–0.25% (ZIRP)",
   balanceSheet:"QE3 continuing — $85B/month",
   regime:"QE3 ongoing. Taper tantrum occurs June 2013 (Bernanke hints at tapering). Gold collapses. TLT sold off. Despite regime still QE+Low, market anticipates exit.",
   rationale:"Paid the price for defensiveness. GLD -26.5%, TLT -8.9%, EEM -13.2% — all three hurt by taper tantrum. QQQ and healthcare positive. AAPL -25% on product cycle concerns. JNJ, PG, MSFT positive. Key lesson: market can price the next regime before it arrives.",
   anchor:"TLT 10%, GLD 10% — both hurt by taper tantrum in June",
   beta:"QQQ 10%, EEM 10% — mixed results",
   alpha:"JNJ 10%, PG 10%, MSFT 10% — quality held up"
  },
  {id:"S2-2013",label:"S2 2013",year:2013,half:2,
   quadrant:"transition",
   quadrantLabel:"Transition",
   fedRate:"0.00–0.25% (ZIRP)",
   balanceSheet:"QE3 tapering announced Dec 2013",
   regime:"Tapering officially announced December 2013. QE being phased out. ZIRP maintained. Market initially feared this, then embraced it — equities surged as economy proved robust.",
   rationale:"Pivoted aggressively to growth post-tantrum. QQQ at 15%, added XLY, XLK, XLV. Dropped gold and TLT. AAPL returned, GOOG and AMZN at high conviction. The correct read: tapering = confidence in economy = bullish equities.",
   anchor:"TLT 5% — reduced drastically, only residual bond hedge",
   beta:"QQQ 15%, XLY 10%, XLK 10%, XLV 10%, EEM 10% — broad equity expansion",
   alpha:"AAPL 10%, GOOG 10%, AMZN 10%, JNJ 10% — growth leaders"
  },
  {id:"S1-2014",label:"S1 2014",year:2014,half:1,
   quadrant:"qe-low",
   quadrantLabel:"QE + Zero Rates",
   fedRate:"0.00–0.25% (ZIRP)",
   balanceSheet:"Tapering in progress — $10B/month reduction",
   regime:"QE tapering ongoing — $10B per meeting reduction. ZIRP maintained. Economy strong. Markets rising. A managed withdrawal from QE while keeping rates at zero.",
   rationale:"Maintained growth/quality tilt. QQQ at 15%. Tech (XLK) and healthcare (XLV) core. TLT still at 5% as insurance given rising rate expectations. AAPL recovering, GOOG steady, AMZN volatile. UNH added for healthcare alpha.",
   anchor:"TLT 5% — minimal duration hedge in tapering environment",
   beta:"QQQ 15%, XLY 10%, XLK 10%, XLV 10%, EEM 10% — diversified growth beta",
   alpha:"AAPL 10%, GOOG 10%, AMZN 10%, JNJ 10%, UNH 10% — growth + quality"
  },
  {id:"S2-2014",label:"S2 2014",year:2014,half:2,
   quadrant:"qt-low",
   quadrantLabel:"QT + Zero Rates",
   fedRate:"0.00–0.25% (ZIRP)",
   balanceSheet:"QE ends Oct 2014 — balance sheet plateaus ~$4.5T",
   regime:"QE officially ends October 2014. Balance sheet held constant (passive QT). ZIRP maintained. First time since 2008 with no active asset purchases. Unique quadrant: no QE, no rate hikes.",
   rationale:"QE ending required repositioning. Added XLI and VTI for broader market beta. Kept QQQ and tech core. UNH added — healthcare reform beneficiary. GOOG and AMZN maintained. Exited defensive bonds entirely.",
   anchor:"VTI 5% — broad US market as new anchor without bond hedge",
   beta:"QQQ 15%, XLK 10%, XLY 10%, XLI 10%, XLV 10% — broad equity exposure",
   alpha:"AAPL 10%, GOOG 10%, AMZN 10%, UNH 10% — sector leaders"
  },
  {id:"S1-2015",label:"S1 2015",year:2015,half:1,
   quadrant:"qt-low",
   quadrantLabel:"QT + Zero Rates",
   fedRate:"0.00–0.25% (ZIRP — first hike expected end of year)",
   balanceSheet:"Balance sheet stable ~$4.5T — passive, no active QT",
   regime:"No QE, ZIRP. First rate hike imminent (happens Dec 2015). Market pricing in normalization. Tech and healthcare lead. Dollar strengthening. EM under pressure.",
   rationale:"Stayed aggressive with growth. QQQ core. AMZN +40% in H1 — Amazon Web Services thesis playing out. UNH +21% on ACA beneficiary thesis. XLK and XLV for sector-level exposure. AAPL still held. VTI for broad market floor.",
   anchor:"VTI 5% — broad market floor",
   beta:"QQQ 15%, XLY 10%, XLK 10%, XLV 10%, XLI 10% — diversified growth",
   alpha:"AAPL 10%, GOOG 10%, AMZN 10%, UNH 10% — dominant sector leaders"
  },
  {id:"S2-2015",label:"S2 2015",year:2015,half:2,
   quadrant:"qt-low",
   quadrantLabel:"QT + Zero Rates",
   fedRate:"0.25% (first hike Dec 2015)",
   balanceSheet:"Stable ~$4.5T",
   regime:"First rate hike since 2006 in December 2015. China volatility, commodity crash. ZIRP officially ends. Balance sheet held. Selectivity premium rises — not all stocks benefit.",
   rationale:"Key positioning: held GOOG (+46%) and AMZN (+56%) which drove the period. Added XLF anticipating rate hike benefit to banks. Dropped UNH (took profits). Despite volatile market (China fears), select mega-caps outperformed massively. Concentrated conviction paid.",
   anchor:"VTI 5% — broad market floor for diversification",
   beta:"QQQ 15%, XLK 10%, XLY 10%, XLV 10%, XLF 10% — broad sector exposure",
   alpha:"AAPL 10%, GOOG 10%, AMZN 10%, UNH 10% — mega-cap tech dominance"
  },
  {id:"S1-2016",label:"S1 2016",year:2016,half:1,
   quadrant:"qt-low",
   quadrantLabel:"QT + Zero Rates",
   fedRate:"0.25–0.50% (slow hiking cycle)",
   balanceSheet:"Stable — no QE or QT",
   regime:"Slow hiking cycle begins. China fears at start of year (circuit breakers). Oil collapses to $26. Then strong recovery — Fed signals only 2 hikes in 2016 vs. originally 4. Selective environment.",
   rationale:"Maintained tech/growth bias through volatile start to year. Dropped UNH after large gains. Added back GOOG, AMZN, AAPL. XLF for bank sector leverage to rate hikes. VTI for broad exposure. Quality names rewarded.",
   anchor:"VTI 5% — broad equity floor",
   beta:"QQQ 15%, XLK 10%, XLY 10%, XLV 10%, XLF 10% — sector-diversified beta",
   alpha:"AAPL 10%, GOOG 10%, AMZN 10%, UNH 10% — quality growth leaders"
  },
  {id:"S2-2016",label:"S2 2016",year:2016,half:2,
   quadrant:"qt-high",
   quadrantLabel:"QT + Rising Rates",
   fedRate:"0.50% → 0.75% (Trump election boost)",
   balanceSheet:"Stable — no QE or QT",
   regime:"Trump elected November 2016 — 'reflation trade' explodes. Banks, industrials, energy surge. December 2016 Fed hike. Dollar spikes. Rates expectations reprice up sharply. Classic value rotation.",
   rationale:"Captured Trump trade with DBC for commodities and XLU for yield. Dropped pure growth plays. GOOG and AMZN retained as secular growers. JNJ for quality. XLV reduced — Trumpcare uncertainty. The regime called for value/cyclicals over growth.",
   anchor:"XLV 10% — defensive quality amid policy uncertainty",
   beta:"QQQ 15%, XLK 10%, XLY 10%, XLU 10% — diversified with rate beneficiaries",
   alpha:"AAPL 10%, GOOG 10%, AMZN 10%, JNJ 10%, DBC 10% — commodities + quality"
  },
  {id:"S1-2017",label:"S1 2017",year:2017,half:1,
   quadrant:"qt-high",
   quadrantLabel:"QT + Rising Rates",
   fedRate:"0.75% → 1.25% (two hikes)",
   balanceSheet:"Stable — QT announced but not started",
   regime:"Fed hikes twice in H1 2017. Economy firing. QT announced for H2. Tech dominates. FAANG stocks begin their multi-year dominance. Rate hikes not damaging growth — goldilocks.",
   rationale:"Went maximum growth. QQQ core. Tech and discretionary overweight. VTI for broad participation. AAPL, GOOG, AMZN, JNJ as the alpha sleeve. Financials removed — rates rising slowly, margins not yet dramatically impacted.",
   anchor:"VTI 5% — broad market participation",
   beta:"QQQ 15%, XLK 10%, XLY 10%, XLV 10%, XLF 10% — sector beta",
   alpha:"AAPL 10%, GOOG 10%, AMZN 10%, JNJ 10% — quality growth at reasonable valuations"
  },
  {id:"S2-2017",label:"S2 2017",year:2017,half:2,
   quadrant:"qt-high",
   quadrantLabel:"QT + Rising Rates",
   fedRate:"1.25% → 1.50%",
   balanceSheet:"QT starts Oct 2017 — $10B/month initial pace",
   regime:"QT officially begins October 2017. Gentle start ($10B/month). Rates rising slowly. Markets ignore both — S&P 500 +19% for full year. Tech tax cuts expected (TCJA passed Dec 2017). Maximum confidence.",
   rationale:"Full tech/growth positioning. QQQ at 20%. Tech, discretionary, financials. Added META (then FB) as social media monetization thesis. VTI for breadth. Tax cuts boosted earnings expectations for H2. Strong year despite QT beginning.",
   anchor:"VTI 5% — market breadth exposure",
   beta:"QQQ 20%, XLY 10%, XLK 10%, XLF 10% — high-beta growth",
   alpha:"AAPL 10%, GOOG 10%, AMZN 10%, FB 10% — FAANG concentration"
  },
  {id:"S1-2018",label:"S1 2018",year:2018,half:1,
   quadrant:"qt-high",
   quadrantLabel:"QT + Rising Rates",
   fedRate:"1.50% → 2.00%",
   balanceSheet:"QT accelerating — $30B/month",
   regime:"QT accelerating. Two rate hikes. Trade war begins (tariffs on China). VIX spike February 2018. Tech initially holds, then faces pressure. Peak earnings season.",
   rationale:"Added defensives (XLP) as volatility hedge. XLK and QQQ maintained but XLF removed (yield curve flattening). AAPL, GOOG, AMZN, JNJ — quality core. VTI for broad market floor. The mix was growth with defensive ballast.",
   anchor:"XLP 5% — consumer staples as vol buffer",
   beta:"QQQ 15%, XLK 10%, XLY 10%, XLV 10% — sector exposure with defensive tilt",
   alpha:"AAPL 10%, GOOG 10%, AMZN 10%, JNJ 10% — FAANG quality"
  },
  {id:"S2-2018",label:"S2 2018",year:2018,half:2,
   quadrant:"qt-high",
   quadrantLabel:"QT + Rising Rates",
   fedRate:"2.00% → 2.50%",
   balanceSheet:"QT at $50B/month — full pace",
   regime:"Maximum QT. Q4 2018 crash — S&P -14% in December alone. Fed hikes in December despite market turmoil. The full QT + Rising Rates quadrant shows its destructive force.",
   rationale:"Rotated heavily defensive. XLV, XLP, SHY, VTI as defensive core. QQQ retained but at lower weight. JNJ and PG as quality anchors. GOOG added for quality growth. Exited cyclicals. The model correctly anticipated the defensive rotation needed.",
   anchor:"SHY 5% — short-duration safety as rates peak",
   beta:"QQQ 15%, XLK 10%, XLV 10%, XLP 10% — defensive growth mix",
   alpha:"AAPL 10%, JNJ 10%, PG 10%, GOOG 10% — quality + defensives"
  },
  {id:"S1-2019",label:"S1 2019",year:2019,half:1,
   quadrant:"qt-high",
   quadrantLabel:"QT + Paused Rates",
   fedRate:"2.50% (paused — pivot incoming)",
   balanceSheet:"QT still active but slowing",
   regime:"Fed pivots to dovish. 'Patient' language. Markets recover sharply from Q4 2018 lows. QT still running but rate hike cycle paused. First rate cut expected H2 2019.",
   rationale:"Pivoted back to growth aggressively on Fed pivot signal. QQQ at 15%, XLK and XLV core. AAPL, GOOG, AMZN, JNJ as alpha sleeve. SHY maintained as safety net. The lesson: when Fed pivots dovish, buy growth — don't wait for first cut.",
   anchor:"SHY 5% — residual safety net",
   beta:"QQQ 15%, XLK 10%, XLV 10%, XLP 10% — recovery beta",
   alpha:"AAPL 10%, GOOG 10%, AMZN 10%, JNJ 10% — quality growth compounders"
  },
  {id:"S2-2019",label:"S2 2019",year:2019,half:2,
   quadrant:"qe-low",
   quadrantLabel:"QE + Falling Rates",
   fedRate:"2.50% → 1.75% (three cuts)",
   balanceSheet:"BS expansion starts Sept 2019 (repo crisis) — de facto QE",
   regime:"Three rate cuts + repo market intervention (essentially QE without the name). Classic pre-pandemic goldilocks: growth moderate, rates falling, liquidity injected. S&P +28.9% for full year.",
   rationale:"Full risk-on. Dropped all bonds and defensives. QQQ, XLK, XLY, IWM — maximum growth beta. AAPL, GOOG, AMZN, MSFT as alpha. VTI for breadth. The repo QE signal was correctly read as a new liquidity injection cycle beginning.",
   anchor:"VTI 5% — broad market floor",
   beta:"QQQ 15%, XLK 10%, XLY 10%, XLV 10%, IWM 10% — high-conviction growth beta",
   alpha:"AAPL 10%, GOOG 10%, AMZN 10%, MSFT 10% — mega-cap dominance"
  },
  {id:"S1-2020",label:"S1 2020",year:2020,half:1,
   quadrant:"qe-low",
   quadrantLabel:"QE + Zero Rates",
   fedRate:"1.75% → 0.00–0.25% (emergency cuts)",
   balanceSheet:"Unlimited QE announced March 2020",
   regime:"COVID crash and response. S&P -34% in 33 days, then recovery on unlimited Fed backstop. The most dramatic policy response in history. QE + ZIRP established within weeks of pandemic onset.",
   rationale:"Pre-pandemic allocation was growth-oriented (QQQ, XLK, AMZN, MSFT, GOOG). The crash hit but recovery was fast — held positions through the V-shaped recovery. AMZN +49% as e-commerce exploded. Only 9 positions (10th was zero). Portfolio +49.8% for full 2020.",
   anchor:"XLV 10% — healthcare defensive in pandemic",
   beta:"QQQ 20%, XLK 10%, XLY 10%, VTI 10% — growth into QE recovery",
   alpha:"AAPL 10%, GOOG 10%, AMZN 10%, MSFT 10% — digital economy beneficiaries"
  },
  {id:"S2-2020",label:"S2 2020",year:2020,half:2,
   quadrant:"qe-low",
   quadrantLabel:"QE + Zero Rates",
   fedRate:"0.00–0.25% (ZIRP)",
   balanceSheet:"Fed BS at ~$7T — $120B/month purchases",
   regime:"Post-crash QE at maximum scale. $120B/month. ZIRP. Fiscal stimulus (CARES). Vaccine news November 2020. Everything goes up — especially speculative. ARKK +170%. NVDA begins AI foreshadowing.",
   rationale:"Added ARKK as speculative upside. Added NVDA (first appearance). AAPL, MSFT, AMZN, XLV core. Portfolio captured the extraordinary H2 2020 rally. QQQ doubled down for Nasdaq leadership.",
   anchor:"XLV 10% — defensive in uncertain recovery",
   beta:"QQQ 20%, XLK 10%, XLY 10% — Nasdaq leadership",
   alpha:"AAPL 10%, MSFT 10%, AMZN 10%, NVDA 10%, ARKK 10% — innovation + mega-cap"
  },
  {id:"S1-2021",label:"S1 2021",year:2021,half:1,
   quadrant:"qe-low",
   quadrantLabel:"QE + Zero Rates",
   fedRate:"0.00–0.25% (ZIRP)",
   balanceSheet:"$120B/month QE — peak stimulus",
   regime:"Peak QE era. Reopening trade. Cyclicals surge (XLF +24%, XLI +16%). NVDA +53%. Meme stocks. SPACs. Everything rising. Classic late-QE euphoria with rotation from pure tech to cyclicals.",
   rationale:"Diversified across cyclicals for reopening. ARKK and QQQ for growth/innovation. XLF, XLI, XLY for reopening beta. NVDA at 10% — GPU demand for AI/crypto/gaming all accelerating. MSFT +22%. Broad participation with tech and cyclicals both working.",
   anchor:"XLV 5% — minimal defensive given euphoric environment",
   beta:"QQQ 15%, ARKK 10%, XLY 10%, XLI 10%, XLF 10% — reopening + innovation",
   alpha:"AAPL 10%, AMZN 10%, MSFT 10%, NVDA 10% — mega-cap + AI seeds"
  },
  {id:"S2-2021",label:"S2 2021",year:2021,half:2,
   quadrant:"transition",
   quadrantLabel:"Transition",
   fedRate:"0.00–0.25% (ZIRP — taper begins Nov)",
   balanceSheet:"Taper starts Nov 2021 — QE being phased out",
   regime:"Tapering announced November 2021. Inflation hits 7% — Fed admits it's not transitory. Markets still up but rotation begins. ARKK collapses from peaks. Quality starts outperforming speculation.",
   rationale:"Rotated to quality — dropped ARKK, added GOOG and JPM. XLK, XLF, XLI, XLV, VTI for sector diversification. AAPL +30%, MSFT +24%, GOOG +15%. The portfolio correctly shed speculative ARK for quality ahead of the taper.",
   anchor:"VTI 10% — broad market as tapering begins",
   beta:"XLK 10%, XLF 10%, XLI 10%, XLE 10%, XLV 10% — sector rotation to value/quality",
   alpha:"AAPL 10%, MSFT 10%, GOOG 10%, JPM 10% — quality compounders"
  },
  {id:"S1-2022",label:"S1 2022",year:2022,half:1,
   quadrant:"qt-high",
   quadrantLabel:"QT + Rising Rates",
   fedRate:"0.25% → 1.75% (fastest hiking cycle since 1994)",
   balanceSheet:"QE ends March 2022 — QT to follow",
   regime:"Inflation shock. Fed hikes 150bps in H1 2022. QE ends. QT announced for June. Nasdaq -30%. S&P -20%. The most aggressive tightening in 40 years begins. Full QT+Rates regime.",
   rationale:"Decisive defensive pivot. XLE at 15% — energy was the only sector with positive returns (+40%). XLF, XLV, XLP, VTV as value/defensive core. CVX for energy alpha. AAPL and MSFT held but hurt (-23% and -24%). SHY for capital preservation. The energy call was the key insight.",
   anchor:"SHY 5% — short-duration cash-like protection",
   beta:"XLE 15%, XLF 10%, XLV 10%, XLP 10%, VTV 10% — value/defensive in rate shock",
   alpha:"AAPL 10%, MSFT 10%, JNJ 10%, CVX 10% — quality + energy"
  },
  {id:"S2-2022",label:"S2 2022",year:2022,half:2,
   quadrant:"qt-high",
   quadrantLabel:"QT + Rising Rates",
   fedRate:"2.50% → 4.50%",
   balanceSheet:"QT active — $95B/month",
   regime:"QT at full pace. Rates rising to 4.5%. Yield curve deeply inverted. Real yields positive. Everything re-priced lower. Duration assets crushed. Full restrictive regime.",
   rationale:"Maximum defensive. XLP at 15% (staples outperform in recession). XLV, VTV, XLE, SHY as core defensive. TIP for inflation protection. CVX +24%. PG +5%. Energy still working. Avoided tech and growth entirely. The most defensive portfolio in the 20-year history.",
   anchor:"SHY 10%, TIP 5% — dual protection: duration + inflation",
   beta:"XLP 15%, XLV 10%, VTV 10%, XLE 10% — maximum defensive posture",
   alpha:"JNJ 10%, PG 10%, CVX 10%, MSFT 10% — defensive quality"
  },
  {id:"S1-2023",label:"S1 2023",year:2023,half:1,
   quadrant:"qt-high",
   quadrantLabel:"QT + High Rates",
   fedRate:"4.50% → 5.25%",
   balanceSheet:"QT active — reducing balance sheet",
   regime:"Rates reach 5.25% — cycle peak. QT continuing. AI narrative explodes (ChatGPT launches Nov 2022, NVDA surges). Market re-rates tech on AI despite restrictive regime. Exceptional year for selective growth.",
   rationale:"Held defensive posture into the year (VTV, XLV, XLP, SHY, TIP) but added XLK for AI exposure. AAPL +49%, MSFT +42% as AI plays. The key insight: AI narrative can overcome rate pressure for quality tech. JNJ and PG as defensive anchors.",
   anchor:"SHY 10%, TIP 10% — capital preservation + inflation",
   beta:"VTV 15%, XLV 10%, XLP 10%, XLK 5% — defensive + selective growth",
   alpha:"AAPL 10%, MSFT 10%, JNJ 10%, PG 10% — quality in rate storm"
  },
  {id:"S2-2023",label:"S2 2023",year:2023,half:2,
   quadrant:"qt-high",
   quadrantLabel:"QT + High Rates",
   fedRate:"5.25–5.50% (peak)",
   balanceSheet:"QT continuing but market front-runs cuts",
   regime:"Rates at peak. Market anticipates cuts in 2024. AI boom in full swing. NVDA +170% in H2. QQQ +35%. The rate peak trade: buy long-duration growth anticipating the pivot.",
   rationale:"Complete rotation to AI/growth. QQQ at 20%, SMH at 10% (semiconductors for AI). NVDA at 10% — the AI infrastructure play. XLV maintained as ballast. Dropped all defensives and bonds. The pivot to AI-driven growth was the defining call of H2 2023.",
   anchor:"XLV 10% — only defensive retained as portfolio pivots to AI",
   beta:"QQQ 20%, XLK 10%, SMH 10%, XLY 5%, VTI 5% — AI-driven beta",
   alpha:"NVDA 10%, AAPL 10%, MSFT 10%, GOOG 10% — AI infrastructure leaders"
  },
  {id:"S1-2024",label:"S1 2024",year:2024,half:1,
   quadrant:"transition",
   quadrantLabel:"Transition",
   fedRate:"5.50% → 5.50% (held — cuts expected H2)",
   balanceSheet:"QT slowing — Fed signals tapering QT",
   regime:"Rates held while market prices cuts. QT pace reduced. AI mega-cap dominance. Magnificent 7 diverge from rest of market. NVDA +149% in H1 alone. Selective inflation in AI semiconductors.",
   rationale:"SMH at 10% — NVDA +149%, SMH best ETF in H1. QQQ and XLI for broad growth. IWM and EEM for breadth. IEI added for first time — anticipating rate cuts. NVDA at 10% as AI infra thesis. MSFT, GOOG, AMZN for quality growth.",
   anchor:"IEI 10% — first bond in portfolio in years, anticipating rate cuts",
   beta:"QQQ 15%, SMH 10%, XLI 10%, IWM 10% — broad + semiconductor",
   alpha:"NVDA 10%, MSFT 10%, GOOG 10%, AMZN 10% — AI infrastructure dominance"
  },
  {id:"S2-2024",label:"S2 2024",year:2024,half:2,
   quadrant:"qt-low",
   quadrantLabel:"QT + Falling Rates",
   fedRate:"5.50% → 4.75% (three cuts begin Sept)",
   balanceSheet:"QT pace reduced — approaching end",
   regime:"Fed begins cutting cycle September 2024. Three cuts in H2. QT still running but pace reduced. Risk-on resumes. Small caps and cyclicals bounce. AI theme broadens.",
   rationale:"Kept SMH and QQQ. Added XLK and META (Facebook AI+advertising). IEI maintained for rate cut benefit. IWM and XLI for cyclical recovery. NVDA and MSFT as AI core. GOOG retained. Dropped VTI — more conviction on specific themes.",
   anchor:"IEI 10% — duration benefiting from rate cuts",
   beta:"QQQ 15%, SMH 10%, IWM 10%, XLI 10% — growth + cyclical recovery",
   alpha:"NVDA 10%, MSFT 10%, GOOG 10%, META 10% — AI monetization"
  },
  {id:"S1-2025",label:"S1 2025",year:2025,half:1,
   quadrant:"transition",
   quadrantLabel:"Transition",
   fedRate:"4.75% → 4.25%",
   balanceSheet:"QT nearly complete — reserves stabilizing",
   regime:"Rate cuts continuing but slower pace. QT nearly done. AI monetization maturing — from infrastructure to applications. NVDA +17.6%, META +26%, SMH +15%. Economy resilient. Inflation re-accelerating concern.",
   rationale:"Maintained AI core (NVDA, MSFT, SMH, QQQ). EEM added — dollar weakness/EM recovery theme. IEI retained for duration. META +26% on AI advertising monetization. VTI for breadth. IWM for small cap rate sensitivity.",
   anchor:"IEI 10% — rate cut beneficiary",
   beta:"QQQ 15%, SMH 10%, IWM 10%, EEM 10%, VTI 5% — diversified global beta",
   alpha:"NVDA 10%, MSFT 10%, AMZN 10%, META 10% — AI ecosystem"
  },
  {id:"S2-2025",label:"S2 2025",year:2025,half:2,
   quadrant:"transition",
   quadrantLabel:"Transition",
   fedRate:"4.25% → 3.75%",
   balanceSheet:"QT ended — balance sheet stable",
   regime:"QT complete. Rate cuts continuing. Balance sheet begins passive expansion via reinvestment. Transition toward QE+Low quadrant. Stagflation risk emerges in Q4 2025 on energy/tariff shock.",
   rationale:"Maintained same core. QQQ, SMH, IWM, EEM for beta. NVDA, MSFT, AMZN, META for alpha. IEI as anchor. Solid H2: SMH +29%, IWM +14%, EEM +13%, NVDA +18%. Only META -11% as advertising faced macro headwinds.",
   anchor:"IEI 10% — duration anchor in easing cycle",
   beta:"QQQ 15%, SMH 10%, IWM 10%, EEM 10%, VTI 5% — consistent with S1",
   alpha:"NVDA 10%, MSFT 10%, AMZN 10%, META 10% — held through META drawdown"
  },
  {id:"S1-2026",label:"S1 2026",year:2026,half:1,
   quadrant:"transition",
   quadrantLabel:"Transition → Expanding Liquidity",
   fedRate:"3.50–3.75% (pause — cuts expected H2)",
   balanceSheet:"~$6.6T — QT complete, balance sheet stabilising",
   regime:"MRM Score 7.7/10 — 'Thin Ice'. QT done, balance sheet stable. Rates paused at 3.75%. ERP compressed at 1%. Market Cap/M2 at 310% — historically expensive. Regime transitioning In-Between to Most Liquid.",
   rationale:"Score 7.7 forced Moderado profile. Portfolio anchored with IEI + XLV for protection. SMH +69.83% was the standout contributor. EEM +22.81% and IWM +21.80% on EM/small cap recovery. Drag from TSLA -23% and META -5%. QQQ slightly negative. Overall: +11.27% vs S&P +6.90%.",
   anchor:"IEI 10%, XLV 5% — dual protection: duration + defensive equity",
   beta:"QQQ 15%, SMH 10%, IWM 10%, EEM 10% — diversified with EM/semis outperforming",
   alpha:"AMZN 10%, GOOG 10%, META 10%, TSLA 10% — growth mix; TSLA detracted"
  },
  {id:"S2-2026",label:"S2 2026",year:2026,half:2,
   quadrant:"transition",
   quadrantLabel:"In Between (Superior Direito)",
   fedRate:"3.50–3.75% (hold, bias subida — possivel hike Jul)",
   balanceSheet:"$6.79T — QT terminou, ligeiramente expansivo",
   regime:"MRM Score 6.65/10 — 'Gelo Muito Fino'. Fed hawkish (Warsh). CPI 4.2% maximo desde Abr 2023. ERP comprimido (~0.85%). BS estabilizou — unico pilar favoravel. Regra dos 3: 1/3 activos (CPI).",
   rationale:"Score 6.65 impos Perfil B Moderado. Portfolio centrado em AI Infrastructure secular (NVDA 12%, AVGO 10%, MSFT 10%) com ancoragem reforcada (SPY 20%) e cash explicito (BIL 7% a 3.75% yield — com ERP simples negativo). Saida de TSLA, energia e ouro. Entrada de GOOG como re-rating value play (P/E 20x). Datas criticas: CPI Jun (14 Jul) e FOMC Jul (29 Jul — possivel hike).",
   anchor:"SPY 20% + BIL 7% — broad market anchor + cash explicito com ERP negativo",
   beta:"QQQ 10%, VGT 8%, BIL 7% — tech quality + cash estrutural",
   alpha:"MSFT 10%, NVDA 12%, AVGO 10%, AMZN 9%, GOOG 9%, META 5% — AI Infrastructure + Quality Compounders"
  }
];

const QUADRANTS = {
  "qe-low":   {label:"QE + Low Rates",    color:"#1e6b4a", accent:"#4ade80", tag:"Maximum Stimulus"},
  "qe-high":  {label:"QE + High Rates",   color:"#6b4e1e", accent:"#fb923c", tag:"Hybrid"},
  "qt-high":  {label:"QT + Rising Rates", color:"#6b1e1e", accent:"#f87171", tag:"Full Restriction"},
  "qt-low":   {label:"QT + Low Rates",    color:"#1e3a6b", accent:"#60a5fa", tag:"Normalization"},
  "transition":{label:"Transition",       color:"#3a1e6b", accent:"#a78bfa", tag:"In-Between"},
};


const HOLDINGS = {"S1 2005": [{"ticker": "XLV", "weight": 15.0, "ret": 2.78}, {"ticker": "XLP", "weight": 10.0, "ret": -1.73}, {"ticker": "XLE", "weight": 15.0, "ret": 22.38}, {"ticker": "VTV", "weight": 10.0, "ret": 0.73}, {"ticker": "TLT", "weight": 5.0, "ret": 9.2}, {"ticker": "SHY", "weight": 5.0, "ret": -0.23}, {"ticker": "JNJ", "weight": 10.0, "ret": 2.49}, {"ticker": "XOM", "weight": 10.0, "ret": 12.11}, {"ticker": "KO", "weight": 10.0, "ret": 0.26}, {"ticker": "PG", "weight": 10.0, "ret": -4.23}], "S2 2005": [{"ticker": "XLE", "weight": 20.0, "ret": 13.18}, {"ticker": "XLV", "weight": 10.0, "ret": 2.22}, {"ticker": "XLP", "weight": 10.0, "ret": 2.37}, {"ticker": "VTV", "weight": 10.0, "ret": 3.66}, {"ticker": "XLI", "weight": 10.0, "ret": 6.94}, {"ticker": "XOM", "weight": 15.0, "ret": 12.11}, {"ticker": "JNJ", "weight": 10.0, "ret": -7.54}, {"ticker": "PG", "weight": 10.0, "ret": 9.73}, {"ticker": "CAT", "weight": 5.0, "ret": 21.23}], "S1 2006": [{"ticker": "XLE", "weight": 15.0, "ret": 12.8}, {"ticker": "XLV", "weight": 10.0, "ret": -4.67}, {"ticker": "XLP", "weight": 10.0, "ret": 3.86}, {"ticker": "VTV", "weight": 10.0, "ret": 5.26}, {"ticker": "XLB", "weight": 10.0, "ret": 6.01}, {"ticker": "SHY", "weight": 5.0, "ret": -0.65}, {"ticker": "JNJ", "weight": 10.0, "ret": -0.3}, {"ticker": "XOM", "weight": 10.0, "ret": 9.22}, {"ticker": "PG", "weight": 10.0, "ret": -3.94}, {"ticker": "MCD", "weight": 10.0, "ret": -0.36}], "S2 2006": [{"ticker": "XLV", "weight": 15.0, "ret": 10.75}, {"ticker": "XLP", "weight": 10.0, "ret": 7.98}, {"ticker": "VTV", "weight": 10.0, "ret": 13.38}, {"ticker": "XLB", "weight": 10.0, "ret": 8.44}, {"ticker": "XLE", "weight": 10.0, "ret": 3.31}, {"ticker": "XLI", "weight": 5.0, "ret": 3.55}, {"ticker": "JNJ", "weight": 10.0, "ret": 10.18}, {"ticker": "XOM", "weight": 10.0, "ret": 24.91}, {"ticker": "MCD", "weight": 10.0, "ret": 31.93}, {"ticker": "BRK.B", "weight": 10.0, "ret": 20.47}], "S1 2007": [{"ticker": "XLV", "weight": 15.0, "ret": 5.43}, {"ticker": "XLI", "weight": 10.0, "ret": 11.51}, {"ticker": "VTV", "weight": 10.0, "ret": 5.36}, {"ticker": "XLB", "weight": 10.0, "ret": 16.35}, {"ticker": "XLF", "weight": 10.0, "ret": -1.52}, {"ticker": "XLE", "weight": 5.0, "ret": 17.67}, {"ticker": "JNJ", "weight": 10.0, "ret": -6.66}, {"ticker": "BRK.B", "weight": 10.0, "ret": -1.66}, {"ticker": "WFC", "weight": 10.0, "ret": -1.1}, {"ticker": "FCX", "weight": 10.0, "ret": 48.61}], "S2 2007": [{"ticker": "XLV", "weight": 15.0, "ret": 0.0}, {"ticker": "XLP", "weight": 15.0, "ret": 6.47}, {"ticker": "VTV", "weight": 10.0, "ret": -7.65}, {"ticker": "XLE", "weight": 10.0, "ret": 15.02}, {"ticker": "GLD", "weight": 10.0, "ret": 1.68}, {"ticker": "JNJ", "weight": 10.0, "ret": 8.24}, {"ticker": "BRK.B", "weight": 10.0, "ret": 31.37}, {"ticker": "WMT", "weight": 10.0, "ret": -1.21}, {"ticker": "PG", "weight": 10.0, "ret": 19.99}], "S1 2008": [{"ticker": "XLV", "weight": 15.0, "ret": -13.4}, {"ticker": "XLP", "weight": 10.0, "ret": -7.12}, {"ticker": "XLE", "weight": 10.0, "ret": 11.51}, {"ticker": "XLU", "weight": 10.0, "ret": -3.85}, {"ticker": "GLD", "weight": 10.0, "ret": 10.84}, {"ticker": "SHY", "weight": 5.0, "ret": 0.85}, {"ticker": "JNJ", "weight": 10.0, "ret": -3.54}, {"ticker": "PG", "weight": 10.0, "ret": -17.18}, {"ticker": "BRK.B", "weight": 10.0, "ret": -15.29}, {"ticker": "CVX", "weight": 10.0, "ret": 6.21}], "S2 2008": [{"ticker": "XLU", "weight": 15.0, "ret": -28.67}, {"ticker": "XLP", "weight": 15.0, "ret": -10.77}, {"ticker": "GLD", "weight": 15.0, "ret": -5.34}, {"ticker": "SHY", "weight": 10.0, "ret": 2.13}, {"ticker": "TLT", "weight": 5.0, "ret": 29.25}, {"ticker": "JNJ", "weight": 10.0, "ret": -7.01}, {"ticker": "PG", "weight": 10.0, "ret": 1.66}, {"ticker": "BRK.B", "weight": 10.0, "ret": -19.89}, {"ticker": "WMT", "weight": 10.0, "ret": -0.25}], "S1 2009": [{"ticker": "QQQ", "weight": 15.0, "ret": 22.33}, {"ticker": "IWM", "weight": 10.0, "ret": 3.74}, {"ticker": "XLK", "weight": 10.0, "ret": 18.17}, {"ticker": "XLY", "weight": 10.0, "ret": 7.0}, {"ticker": "GLD", "weight": 10.0, "ret": 5.39}, {"ticker": "XLV", "weight": 5.0, "ret": -0.9}, {"ticker": "AAPL", "weight": 10.0, "ret": 66.88}, {"ticker": "AMZN", "weight": 10.0, "ret": 63.14}, {"ticker": "JNJ", "weight": 10.0, "ret": -5.06}, {"ticker": "BRK.B", "weight": 10.0, "ret": -9.9}], "S2 2009": [{"ticker": "QQQ", "weight": 15.0, "ret": 25.76}, {"ticker": "IWM", "weight": 15.0, "ret": 22.24}, {"ticker": "XLY", "weight": 10.0, "ret": 28.99}, {"ticker": "XLF", "weight": 10.0, "ret": 20.5}, {"ticker": "XLK", "weight": 5.0, "ret": 25.92}, {"ticker": "GLD", "weight": 5.0, "ret": 17.69}, {"ticker": "AAPL", "weight": 10.0, "ret": 47.95}, {"ticker": "AMZN", "weight": 10.0, "ret": 60.79}, {"ticker": "GOOG", "weight": 10.0, "ret": 46.0}, {"ticker": "MSFT", "weight": 10.0, "ret": 28.23}], "S1 2010": [{"ticker": "QQQ", "weight": 15.0, "ret": -6.64}, {"ticker": "IWM", "weight": 15.0, "ret": -2.12}, {"ticker": "XLY", "weight": 10.0, "ret": -2.15}, {"ticker": "EEM", "weight": 10.0, "ret": -10.07}, {"ticker": "XLK", "weight": 5.0, "ret": -11.03}, {"ticker": "GLD", "weight": 5.0, "ret": 13.39}, {"ticker": "AAPL", "weight": 10.0, "ret": 19.36}, {"ticker": "AMZN", "weight": 10.0, "ret": -18.78}, {"ticker": "GOOG", "weight": 10.0, "ret": -30.0}, {"ticker": "MSFT", "weight": 10.0, "ret": -24.51}], "S2 2010": [{"ticker": "EEM", "weight": 15.0, "ret": 27.66}, {"ticker": "DBC", "weight": 10.0, "ret": 27.72}, {"ticker": "XLY", "weight": 10.0, "ret": 28.42}, {"ticker": "XLV", "weight": 10.0, "ret": 11.7}, {"ticker": "GLD", "weight": 10.0, "ret": 14.0}, {"ticker": "VTI", "weight": 5.0, "ret": 23.53}, {"ticker": "AAPL", "weight": 10.0, "ret": 28.42}, {"ticker": "GOOG", "weight": 10.0, "ret": 35.0}, {"ticker": "MSFT", "weight": 10.0, "ret": 21.3}, {"ticker": "PG", "weight": 10.0, "ret": 7.25}], "S1 2011": [{"ticker": "EEM", "weight": 15.0, "ret": -0.09}, {"ticker": "DBC", "weight": 10.0, "ret": 5.12}, {"ticker": "QQQ", "weight": 10.0, "ret": 4.76}, {"ticker": "XLY", "weight": 10.0, "ret": 7.48}, {"ticker": "XLK", "weight": 10.0, "ret": 2.02}, {"ticker": "GLD", "weight": 5.0, "ret": 5.25}, {"ticker": "AAPL", "weight": 10.0, "ret": 4.06}, {"ticker": "AMZN", "weight": 10.0, "ret": 13.61}, {"ticker": "GOOG", "weight": 10.0, "ret": -13.0}, {"ticker": "BIDU", "weight": 10.0, "ret": 45.17}], "S2 2011": [{"ticker": "GLD", "weight": 15.0, "ret": 4.1}, {"ticker": "DBC", "weight": 10.0, "ret": -7.32}, {"ticker": "QQQ", "weight": 10.0, "ret": -2.14}, {"ticker": "XLY", "weight": 10.0, "ret": -2.96}, {"ticker": "XLK", "weight": 10.0, "ret": -0.97}, {"ticker": "EEM", "weight": 5.0, "ret": -20.29}, {"ticker": "AAPL", "weight": 10.0, "ret": 20.65}, {"ticker": "AMZN", "weight": 10.0, "ret": -15.35}, {"ticker": "GOOG", "weight": 10.0, "ret": 23.0}, {"ticker": "JNJ", "weight": 10.0, "ret": -1.41}], "S1 2012": [{"ticker": "GLD", "weight": 10.0, "ret": 2.11}, {"ticker": "XLV", "weight": 10.0, "ret": 9.56}, {"ticker": "XLP", "weight": 10.0, "ret": 7.02}, {"ticker": "QQQ", "weight": 10.0, "ret": 14.92}, {"ticker": "EEM", "weight": 10.0, "ret": 3.15}, {"ticker": "TLT", "weight": 10.0, "ret": 3.26}, {"ticker": "AAPL", "weight": 10.0, "ret": 44.2}, {"ticker": "JNJ", "weight": 10.0, "ret": 3.02}, {"ticker": "PG", "weight": 10.0, "ret": -8.18}, {"ticker": "MSFT", "weight": 10.0, "ret": 17.84}], "S2 2012": [{"ticker": "GLD", "weight": 10.0, "ret": 4.4}, {"ticker": "XLV", "weight": 10.0, "ret": 4.93}, {"ticker": "XLP", "weight": 10.0, "ret": 0.37}, {"ticker": "QQQ", "weight": 10.0, "ret": 1.51}, {"ticker": "EEM", "weight": 10.0, "ret": 13.33}, {"ticker": "TLT", "weight": 10.0, "ret": -3.21}, {"ticker": "AAPL", "weight": 10.0, "ret": -8.87}, {"ticker": "JNJ", "weight": 10.0, "ret": 3.76}, {"ticker": "PG", "weight": 10.0, "ret": 10.84}, {"ticker": "MSFT", "weight": 10.0, "ret": -12.68}], "S1 2013": [{"ticker": "GLD", "weight": 10.0, "ret": -26.48}, {"ticker": "XLV", "weight": 10.0, "ret": 19.38}, {"ticker": "XLP", "weight": 10.0, "ret": 13.67}, {"ticker": "QQQ", "weight": 10.0, "ret": 9.43}, {"ticker": "EEM", "weight": 10.0, "ret": -13.19}, {"ticker": "TLT", "weight": 10.0, "ret": -8.86}, {"ticker": "AAPL", "weight": 10.0, "ret": -25.49}, {"ticker": "JNJ", "weight": 10.0, "ret": 22.48}, {"ticker": "PG", "weight": 10.0, "ret": 13.4}, {"ticker": "MSFT", "weight": 10.0, "ret": 29.34}], "S2 2013": [{"ticker": "QQQ", "weight": 15.0, "ret": 23.42}, {"ticker": "XLY", "weight": 10.0, "ret": 18.49}, {"ticker": "XLK", "weight": 10.0, "ret": 16.85}, {"ticker": "XLV", "weight": 10.0, "ret": 16.45}, {"ticker": "EEM", "weight": 10.0, "ret": 8.56}, {"ticker": "TLT", "weight": 5.0, "ret": -7.77}, {"ticker": "AAPL", "weight": 10.0, "ret": 41.48}, {"ticker": "GOOG", "weight": 10.0, "ret": 27.0}, {"ticker": "AMZN", "weight": 10.0, "ret": 43.61}, {"ticker": "JNJ", "weight": 10.0, "ret": 6.67}], "S1 2014": [{"ticker": "QQQ", "weight": 15.0, "ret": 6.76}, {"ticker": "XLY", "weight": 10.0, "ret": -0.13}, {"ticker": "XLK", "weight": 10.0, "ret": 7.3}, {"ticker": "XLV", "weight": 10.0, "ret": 9.72}, {"ticker": "EEM", "weight": 10.0, "ret": 3.43}, {"ticker": "TLT", "weight": 5.0, "ret": 11.45}, {"ticker": "AAPL", "weight": 10.0, "ret": 15.95}, {"ticker": "GOOG", "weight": 10.0, "ret": 4.7}, {"ticker": "AMZN", "weight": 10.0, "ret": -18.56}, {"ticker": "JNJ", "weight": 10.0, "ret": 14.23}], "S2 2014": [{"ticker": "QQQ", "weight": 15.0, "ret": 9.95}, {"ticker": "XLK", "weight": 10.0, "ret": 7.82}, {"ticker": "XLY", "weight": 10.0, "ret": 8.11}, {"ticker": "XLI", "weight": 10.0, "ret": 4.66}, {"ticker": "XLV", "weight": 10.0, "ret": 12.41}, {"ticker": "VTI", "weight": 5.0, "ret": 4.16}, {"ticker": "AAPL", "weight": 10.0, "ret": 18.78}, {"ticker": "GOOG", "weight": 10.0, "ret": -7.9}, {"ticker": "AMZN", "weight": 10.0, "ret": -4.44}, {"ticker": "UNH", "weight": 10.0, "ret": 23.66}], "S1 2015": [{"ticker": "QQQ", "weight": 15.0, "ret": 3.7}, {"ticker": "XLY", "weight": 10.0, "ret": 6.0}, {"ticker": "XLK", "weight": 10.0, "ret": 0.12}, {"ticker": "XLV", "weight": 10.0, "ret": 8.79}, {"ticker": "XLI", "weight": 10.0, "ret": -4.45}, {"ticker": "VTI", "weight": 5.0, "ret": 0.96}, {"ticker": "AAPL", "weight": 10.0, "ret": 13.63}, {"ticker": "GOOG", "weight": 10.0, "ret": -0.85}, {"ticker": "AMZN", "weight": 10.0, "ret": 39.87}, {"ticker": "UNH", "weight": 10.0, "ret": 20.68}], "S2 2015": [{"ticker": "QQQ", "weight": 15.0, "ret": 4.47}, {"ticker": "XLK", "weight": 10.0, "ret": 3.45}, {"ticker": "XLY", "weight": 10.0, "ret": 2.2}, {"ticker": "XLV", "weight": 10.0, "ret": -3.17}, {"ticker": "XLF", "weight": 10.0, "ret": -2.26}, {"ticker": "VTI", "weight": 5.0, "ret": -2.54}, {"ticker": "AAPL", "weight": 10.0, "ret": -16.08}, {"ticker": "GOOG", "weight": 10.0, "ret": 45.8}, {"ticker": "AMZN", "weight": 10.0, "ret": 55.7}, {"ticker": "UNH", "weight": 10.0, "ret": -3.57}], "S1 2016": [{"ticker": "QQQ", "weight": 15.0, "ret": 3.7}, {"ticker": "XLK", "weight": 10.0, "ret": 0.12}, {"ticker": "XLY", "weight": 10.0, "ret": 6.0}, {"ticker": "XLV", "weight": 10.0, "ret": 8.79}, {"ticker": "XLF", "weight": 10.0, "ret": -1.42}, {"ticker": "VTI", "weight": 5.0, "ret": 0.96}, {"ticker": "AAPL", "weight": 10.0, "ret": 13.63}, {"ticker": "GOOG", "weight": 10.0, "ret": -0.85}, {"ticker": "AMZN", "weight": 10.0, "ret": 39.87}, {"ticker": "UNH", "weight": 10.0, "ret": 20.68}], "S2 2016": [{"ticker": "QQQ", "weight": 15.0, "ret": 4.47}, {"ticker": "XLK", "weight": 10.0, "ret": 3.45}, {"ticker": "XLY", "weight": 10.0, "ret": 2.2}, {"ticker": "XLV", "weight": 10.0, "ret": -3.17}, {"ticker": "DBC", "weight": 10.0, "ret": -25.78}, {"ticker": "XLU", "weight": 5.0, "ret": 4.39}, {"ticker": "AAPL", "weight": 10.0, "ret": -16.08}, {"ticker": "GOOG", "weight": 10.0, "ret": 45.8}, {"ticker": "AMZN", "weight": 10.0, "ret": 55.7}, {"ticker": "JNJ", "weight": 10.0, "ret": 5.4}], "S1 2017": [{"ticker": "QQQ", "weight": 15.0, "ret": 16.17}, {"ticker": "XLK", "weight": 10.0, "ret": 13.15}, {"ticker": "XLY", "weight": 10.0, "ret": 10.11}, {"ticker": "XLV", "weight": 10.0, "ret": 14.94}, {"ticker": "XLF", "weight": 10.0, "ret": 6.11}, {"ticker": "VTI", "weight": 5.0, "ret": 7.92}, {"ticker": "AAPL", "weight": 10.0, "ret": 24.35}, {"ticker": "GOOG", "weight": 10.0, "ret": 17.74}, {"ticker": "AMZN", "weight": 10.0, "ret": 29.09}, {"ticker": "JNJ", "weight": 10.0, "ret": 14.83}], "S2 2017": [{"ticker": "QQQ", "weight": 20.0, "ret": 13.16}, {"ticker": "XLY", "weight": 10.0, "ret": 10.11}, {"ticker": "XLK", "weight": 10.0, "ret": 16.87}, {"ticker": "XLF", "weight": 10.0, "ret": 13.13}, {"ticker": "VTI", "weight": 10.0, "ret": 10.29}, {"ticker": "AAPL", "weight": 10.0, "ret": 17.5}, {"ticker": "GOOG", "weight": 10.0, "ret": 15.15}, {"ticker": "AMZN", "weight": 10.0, "ret": 20.81}, {"ticker": "FB", "weight": 10.0, "ret": 16.88}], "S1 2018": [{"ticker": "QQQ", "weight": 15.0, "ret": 10.2}, {"ticker": "XLK", "weight": 10.0, "ret": 8.63}, {"ticker": "XLY", "weight": 10.0, "ret": 10.75}, {"ticker": "XLV", "weight": 10.0, "ret": 0.94}, {"ticker": "XLP", "weight": 10.0, "ret": -9.42}, {"ticker": "VTI", "weight": 5.0, "ret": 2.32}, {"ticker": "AAPL", "weight": 10.0, "ret": 9.38}, {"ticker": "GOOG", "weight": 10.0, "ret": 6.62}, {"ticker": "AMZN", "weight": 10.0, "ret": 45.35}, {"ticker": "JNJ", "weight": 10.0, "ret": -13.15}], "S2 2018": [{"ticker": "XLV", "weight": 15.0, "ret": 3.65}, {"ticker": "XLP", "weight": 10.0, "ret": -1.46}, {"ticker": "QQQ", "weight": 10.0, "ret": -10.13}, {"ticker": "XLK", "weight": 10.0, "ret": -10.78}, {"ticker": "SHY", "weight": 10.0, "ret": 0.3}, {"ticker": "VTI", "weight": 5.0, "ret": -9.11}, {"ticker": "AAPL", "weight": 10.0, "ret": -14.79}, {"ticker": "JNJ", "weight": 10.0, "ret": 6.35}, {"ticker": "PG", "weight": 10.0, "ret": 17.76}, {"ticker": "GOOG", "weight": 10.0, "ret": -7.17}], "S1 2019": [{"ticker": "QQQ", "weight": 15.0, "ret": 21.06}, {"ticker": "XLK", "weight": 10.0, "ret": 25.91}, {"ticker": "XLV", "weight": 10.0, "ret": 7.09}, {"ticker": "XLP", "weight": 10.0, "ret": 14.36}, {"ticker": "SHY", "weight": 10.0, "ret": 1.39}, {"ticker": "VTI", "weight": 5.0, "ret": 17.6}, {"ticker": "AAPL", "weight": 10.0, "ret": 25.47}, {"ticker": "GOOG", "weight": 10.0, "ret": 4.37}, {"ticker": "AMZN", "weight": 10.0, "ret": 26.08}, {"ticker": "JNJ", "weight": 10.0, "ret": 7.93}], "S2 2019": [{"ticker": "QQQ", "weight": 20.0, "ret": 13.85}, {"ticker": "XLK", "weight": 10.0, "ret": 17.47}, {"ticker": "XLY", "weight": 10.0, "ret": 5.22}, {"ticker": "XLV", "weight": 10.0, "ret": 9.95}, {"ticker": "IWM", "weight": 5.0, "ret": 6.54}, {"ticker": "VTI", "weight": 5.0, "ret": 9.01}, {"ticker": "AAPL", "weight": 10.0, "ret": 48.37}, {"ticker": "GOOG", "weight": 10.0, "ret": 23.69}, {"ticker": "AMZN", "weight": 10.0, "ret": -2.42}, {"ticker": "MSFT", "weight": 10.0, "ret": 17.72}], "S1 2020": [{"ticker": "QQQ", "weight": 20.0, "ret": 16.46}, {"ticker": "XLK", "weight": 10.0, "ret": 13.98}, {"ticker": "XLY", "weight": 10.0, "ret": 1.38}, {"ticker": "XLV", "weight": 10.0, "ret": -1.76}, {"ticker": "VTI", "weight": 10.0, "ret": -4.33}, {"ticker": "AAPL", "weight": 10.0, "ret": 24.23}, {"ticker": "GOOG", "weight": 10.0, "ret": 5.73}, {"ticker": "AMZN", "weight": 10.0, "ret": 49.3}, {"ticker": "MSFT", "weight": 10.0, "ret": 29.05}], "S2 2020": [{"ticker": "QQQ", "weight": 20.0, "ret": 26.71}, {"ticker": "XLK", "weight": 10.0, "ret": 24.43}, {"ticker": "XLV", "weight": 10.0, "ret": 13.36}, {"ticker": "XLY", "weight": 10.0, "ret": 25.89}, {"ticker": "ARKK", "weight": 10.0, "ret": 74.58}, {"ticker": "AAPL", "weight": 10.0, "ret": 45.49}, {"ticker": "MSFT", "weight": 10.0, "ret": 9.29}, {"ticker": "AMZN", "weight": 10.0, "ret": 18.06}, {"ticker": "NVDA", "weight": 10.0, "ret": 37.45}], "S1 2021": [{"ticker": "QQQ", "weight": 15.0, "ret": 12.97}, {"ticker": "ARKK", "weight": 10.0, "ret": 5.05}, {"ticker": "XLY", "weight": 10.0, "ret": 11.05}, {"ticker": "XLI", "weight": 10.0, "ret": 15.64}, {"ticker": "XLF", "weight": 10.0, "ret": 24.46}, {"ticker": "XLV", "weight": 5.0, "ret": 11.03}, {"ticker": "AAPL", "weight": 10.0, "ret": 3.22}, {"ticker": "AMZN", "weight": 10.0, "ret": 5.63}, {"ticker": "MSFT", "weight": 10.0, "ret": 21.8}, {"ticker": "NVDA", "weight": 10.0, "ret": 53.22}], "S2 2021": [{"ticker": "XLK", "weight": 10.0, "ret": 17.75}, {"ticker": "XLF", "weight": 10.0, "ret": 6.43}, {"ticker": "XLI", "weight": 10.0, "ret": 3.33}, {"ticker": "XLE", "weight": 10.0, "ret": 3.03}, {"ticker": "XLV", "weight": 10.0, "ret": 11.86}, {"ticker": "VTI", "weight": 10.0, "ret": 8.36}, {"ticker": "AAPL", "weight": 10.0, "ret": 29.65}, {"ticker": "MSFT", "weight": 10.0, "ret": 24.15}, {"ticker": "GOOG", "weight": 10.0, "ret": 15.45}, {"ticker": "JPM", "weight": 10.0, "ret": 1.81}], "S1 2022": [{"ticker": "XLE", "weight": 15.0, "ret": 28.85}, {"ticker": "XLF", "weight": 10.0, "ret": -19.46}, {"ticker": "XLV", "weight": 10.0, "ret": -8.98}, {"ticker": "XLP", "weight": 10.0, "ret": -6.39}, {"ticker": "VTV", "weight": 10.0, "ret": -10.35}, {"ticker": "SHY", "weight": 5.0, "ret": -3.21}, {"ticker": "AAPL", "weight": 10.0, "ret": -23.01}, {"ticker": "MSFT", "weight": 10.0, "ret": -23.64}, {"ticker": "JNJ", "weight": 10.0, "ret": 3.76}, {"ticker": "CVX", "weight": 10.0, "ret": 23.37}], "S2 2022": [{"ticker": "XLP", "weight": 15.0, "ret": 3.28}, {"ticker": "XLV", "weight": 10.0, "ret": 5.93}, {"ticker": "VTV", "weight": 10.0, "ret": 6.44}, {"ticker": "XLE", "weight": 10.0, "ret": 22.32}, {"ticker": "SHY", "weight": 10.0, "ret": -1.96}, {"ticker": "TIP", "weight": 5.0, "ret": -6.56}, {"ticker": "JNJ", "weight": 10.0, "ret": -0.48}, {"ticker": "PG", "weight": 10.0, "ret": 5.4}, {"ticker": "CVX", "weight": 10.0, "ret": 23.97}, {"ticker": "MSFT", "weight": 10.0, "ret": -6.62}], "S1 2023": [{"ticker": "VTV", "weight": 15.0, "ret": 1.23}, {"ticker": "XLV", "weight": 10.0, "ret": -2.3}, {"ticker": "XLP", "weight": 10.0, "ret": -0.51}, {"ticker": "SHY", "weight": 10.0, "ret": -0.11}, {"ticker": "TIP", "weight": 10.0, "ret": 1.11}, {"ticker": "XLK", "weight": 5.0, "ret": 39.71}, {"ticker": "AAPL", "weight": 10.0, "ret": 49.29}, {"ticker": "MSFT", "weight": 10.0, "ret": 42.0}, {"ticker": "JNJ", "weight": 10.0, "ret": -6.3}, {"ticker": "PG", "weight": 10.0, "ret": 0.12}], "S2 2023": [{"ticker": "QQQ", "weight": 20.0, "ret": 38.73}, {"ticker": "XLK", "weight": 10.0, "ret": 10.71}, {"ticker": "SMH", "weight": 10.0, "ret": 50.04}, {"ticker": "XLV", "weight": 10.0, "ret": 2.75}, {"ticker": "XLY", "weight": 5.0, "ret": 31.47}, {"ticker": "VTI", "weight": 5.0, "ret": 15.22}, {"ticker": "NVDA", "weight": 10.0, "ret": 17.07}, {"ticker": "AAPL", "weight": 10.0, "ret": -0.74}, {"ticker": "MSFT", "weight": 10.0, "ret": 10.42}, {"ticker": "GOOG", "weight": 10.0, "ret": 16.5}], "S1 2024": [{"ticker": "QQQ", "weight": 15.0, "ret": 16.99}, {"ticker": "SMH", "weight": 10.0, "ret": 49.08}, {"ticker": "XLI", "weight": 10.0, "ret": 6.91}, {"ticker": "IWM", "weight": 10.0, "ret": 1.09}, {"ticker": "IEI", "weight": 10.0, "ret": -1.42}, {"ticker": "VTI", "weight": 5.0, "ret": 12.77}, {"ticker": "NVDA", "weight": 10.0, "ret": 149.46}, {"ticker": "MSFT", "weight": 10.0, "ret": 18.86}, {"ticker": "GOOG", "weight": 10.0, "ret": 30.15}, {"ticker": "AMZN", "weight": 10.0, "ret": 27.19}], "S2 2024": [{"ticker": "QQQ", "weight": 15.0, "ret": 6.7}, {"ticker": "SMH", "weight": 10.0, "ret": -7.11}, {"ticker": "IWM", "weight": 10.0, "ret": 8.91}, {"ticker": "XLI", "weight": 10.0, "ret": 8.12}, {"ticker": "IEI", "weight": 10.0, "ret": 0.07}, {"ticker": "XLK", "weight": 5.0, "ret": 7.0}, {"ticker": "NVDA", "weight": 10.0, "ret": 8.7}, {"ticker": "MSFT", "weight": 10.0, "ret": -5.69}, {"ticker": "GOOG", "weight": 10.0, "ret": 3.83}, {"ticker": "META", "weight": 10.0, "ret": 16.12}], "S1 2025": [{"ticker": "QQQ", "weight": 15.0, "ret": 7.9}, {"ticker": "SMH", "weight": 10.0, "ret": 15.16}, {"ticker": "IWM", "weight": 10.0, "ret": -2.34}, {"ticker": "EEM", "weight": 10.0, "ret": 15.35}, {"ticker": "IEI", "weight": 10.0, "ret": 3.06}, {"ticker": "VTI", "weight": 5.0, "ret": 4.87}, {"ticker": "NVDA", "weight": 10.0, "ret": 17.65}, {"ticker": "MSFT", "weight": 10.0, "ret": 18.01}, {"ticker": "AMZN", "weight": 10.0, "ret": 0.0}, {"ticker": "META", "weight": 10.0, "ret": 26.06}], "S2 2025": [{"ticker": "QQQ", "weight": 15.0, "ret": 11.36}, {"ticker": "SMH", "weight": 10.0, "ret": 29.13}, {"ticker": "IWM", "weight": 10.0, "ret": 14.07}, {"ticker": "EEM", "weight": 10.0, "ret": 13.41}, {"ticker": "IEI", "weight": 10.0, "ret": 0.22}, {"ticker": "VTI", "weight": 5.0, "ret": 10.31}, {"ticker": "NVDA", "weight": 10.0, "ret": 18.05}, {"ticker": "MSFT", "weight": 10.0, "ret": -2.77}, {"ticker": "AMZN", "weight": 10.0, "ret": 5.21}, {"ticker": "META", "weight": 10.0, "ret": -10.57}],
"S1 2026": [
  {"ticker": "AMZN", "weight": 10.0, "ret": 0.81},
  {"ticker": "GOOG", "weight": 10.0, "ret": 6.66},
  {"ticker": "TSLA", "weight": 10.0, "ret": -15.57},
  {"ticker": "META", "weight": 10.0, "ret": -16.64},
  {"ticker": "XLV",  "weight": 5.0,  "ret": 3.58},
  {"ticker": "IEI",  "weight": 10.0, "ret": -1.29},
  {"ticker": "EEM",  "weight": 10.0, "ret": 22.81},
  {"ticker": "IWM",  "weight": 10.0, "ret": 21.80},
  {"ticker": "SMH",  "weight": 10.0, "ret": 69.83},
  {"ticker": "QQQ",  "weight": 15.0, "ret": 15.01}
],
"S2 2026": [
  {"ticker": "SPY",  "weight": 20.0, "ret": 0.0},
  {"ticker": "QQQ",  "weight": 10.0, "ret": 0.0},
  {"ticker": "VGT",  "weight": 8.0,  "ret": 0.0},
  {"ticker": "BIL",  "weight": 7.0,  "ret": 0.0},
  {"ticker": "MSFT", "weight": 10.0, "ret": 0.0},
  {"ticker": "NVDA", "weight": 12.0, "ret": 0.0},
  {"ticker": "AVGO", "weight": 10.0, "ret": 0.0},
  {"ticker": "AMZN", "weight": 9.0,  "ret": 0.0},
  {"ticker": "GOOG", "weight": 9.0,  "ret": 0.0},
  {"ticker": "META", "weight": 5.0,  "ret": 0.0}
]};

const ANNUAL_PERF = {"2005": {"portfolio": 12.81, "sp500": 3.0, "pv": 225627, "sv": 206000}, "2006": {"portfolio": 17.72, "sp500": 13.62, "pv": 265599, "sv": 234057}, "2007": {"portfolio": 17.18, "sp500": 3.53, "pv": 311227, "sv": 242319}, "2008": {"portfolio": -11.11, "sp500": -38.49, "pv": 276647, "sv": 149051}, "2009": {"portfolio": 56.82, "sp500": 23.45, "pv": 433833, "sv": 184003}, "2010": {"portfolio": 13.12, "sp500": 12.78, "pv": 490760, "sv": 207519}, "2011": {"portfolio": 8.19, "sp500": 0.0, "pv": 530952, "sv": 207519}, "2012": {"portfolio": 11.27, "sp500": 13.41, "pv": 590776, "sv": 235347}, "2013": {"portfolio": 25.11, "sp500": 29.6, "pv": 739131, "sv": 305010}, "2014": {"portfolio": 13.68, "sp500": 11.39, "pv": 840256, "sv": 339750}, "2015": {"portfolio": 18.52, "sp500": -0.73, "pv": 995859, "sv": 337270}, "2016": {"portfolio": 17.64, "sp500": 9.54, "pv": 1171494, "sv": 369446}, "2017": {"portfolio": 32.89, "sp500": 19.42, "pv": 1556809, "sv": 441192}, "2018": {"portfolio": 5.51, "sp500": -6.24, "pv": 1642627, "sv": 413662}, "2019": {"portfolio": 33.23, "sp500": 28.88, "pv": 2188392, "sv": 533127}, "2020": {"portfolio": 49.79, "sp500": 16.26, "pv": 3278028, "sv": 619813}, "2021": {"portfolio": 30.7, "sp500": 26.89, "pv": 4284268, "sv": 786481}, "2022": {"portfolio": 3.23, "sp500": -19.44, "pv": 4422674, "sv": 633589}, "2023": {"portfolio": 33.43, "sp500": 24.23, "pv": 5901387, "sv": 787108}, "2024": {"portfolio": 37.43, "sp500": 23.31, "pv": 8110001, "sv": 970583}, "2025": {"portfolio": 20.57, "sp500": 16.35, "pv": 9778375, "sv": 1129273}, "2026": {"portfolio": 11.27, "sp500": 6.9, "pv": 10880398, "sv": 1207193}};
